// flow-typed signature: 15307be8860723b29cf2696ce40db6eb
// flow-typed version: <<STUB>>/command-line-args_v3.0.4/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'command-line-args'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'command-line-args' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'command-line-args/bin' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/bin/cli' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/lib/argv' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/lib/command-line-args' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/lib/definition' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/lib/definitions' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/lib/option' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/alias' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/ambiguous-input' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/bad-input' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/class-argv' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/class-definitions' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/default-option' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/default-value' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/detect-process-argv' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/exceptions' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/grouping' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/name-alias-mix' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/name-unicode' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/notations' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/option' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/type-boolean-multiple' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/type-boolean' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/type-none' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/type-number-multiple' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/type-number' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/type-other-multiple' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/type-other' {
  declare module.exports: any;
}

declare module 'command-line-args/es5/test/type-string' {
  declare module.exports: any;
}

declare module 'command-line-args/example/alias' {
  declare module.exports: any;
}

declare module 'command-line-args/example/defaultValue' {
  declare module.exports: any;
}

declare module 'command-line-args/example/group' {
  declare module.exports: any;
}

declare module 'command-line-args/example/multiple' {
  declare module.exports: any;
}

declare module 'command-line-args/example/name' {
  declare module.exports: any;
}

declare module 'command-line-args/example/type' {
  declare module.exports: any;
}

declare module 'command-line-args/example/typical' {
  declare module.exports: any;
}

declare module 'command-line-args/example/validate' {
  declare module.exports: any;
}

declare module 'command-line-args/src/bin/cli' {
  declare module.exports: any;
}

declare module 'command-line-args/src/lib/argv' {
  declare module.exports: any;
}

declare module 'command-line-args/src/lib/command-line-args' {
  declare module.exports: any;
}

declare module 'command-line-args/src/lib/definition' {
  declare module.exports: any;
}

declare module 'command-line-args/src/lib/definitions' {
  declare module.exports: any;
}

declare module 'command-line-args/src/lib/option' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/alias' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/ambiguous-input' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/bad-input' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/class-argv' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/class-definitions' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/default-option' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/default-value' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/detect-process-argv' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/exceptions' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/grouping' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/name-alias-mix' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/name-unicode' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/notations' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/option' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/type-boolean-multiple' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/type-boolean' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/type-none' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/type-number-multiple' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/type-number' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/type-other-multiple' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/type-other' {
  declare module.exports: any;
}

declare module 'command-line-args/src/test/type-string' {
  declare module.exports: any;
}

declare module 'command-line-args/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'command-line-args/bin.js' {
  declare module.exports: $Exports<'command-line-args/bin'>;
}
declare module 'command-line-args/es5/bin/cli.js' {
  declare module.exports: $Exports<'command-line-args/es5/bin/cli'>;
}
declare module 'command-line-args/es5/lib/argv.js' {
  declare module.exports: $Exports<'command-line-args/es5/lib/argv'>;
}
declare module 'command-line-args/es5/lib/command-line-args.js' {
  declare module.exports: $Exports<'command-line-args/es5/lib/command-line-args'>;
}
declare module 'command-line-args/es5/lib/definition.js' {
  declare module.exports: $Exports<'command-line-args/es5/lib/definition'>;
}
declare module 'command-line-args/es5/lib/definitions.js' {
  declare module.exports: $Exports<'command-line-args/es5/lib/definitions'>;
}
declare module 'command-line-args/es5/lib/option.js' {
  declare module.exports: $Exports<'command-line-args/es5/lib/option'>;
}
declare module 'command-line-args/es5/test/alias.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/alias'>;
}
declare module 'command-line-args/es5/test/ambiguous-input.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/ambiguous-input'>;
}
declare module 'command-line-args/es5/test/bad-input.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/bad-input'>;
}
declare module 'command-line-args/es5/test/class-argv.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/class-argv'>;
}
declare module 'command-line-args/es5/test/class-definitions.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/class-definitions'>;
}
declare module 'command-line-args/es5/test/default-option.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/default-option'>;
}
declare module 'command-line-args/es5/test/default-value.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/default-value'>;
}
declare module 'command-line-args/es5/test/detect-process-argv.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/detect-process-argv'>;
}
declare module 'command-line-args/es5/test/exceptions.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/exceptions'>;
}
declare module 'command-line-args/es5/test/grouping.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/grouping'>;
}
declare module 'command-line-args/es5/test/name-alias-mix.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/name-alias-mix'>;
}
declare module 'command-line-args/es5/test/name-unicode.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/name-unicode'>;
}
declare module 'command-line-args/es5/test/notations.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/notations'>;
}
declare module 'command-line-args/es5/test/option.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/option'>;
}
declare module 'command-line-args/es5/test/type-boolean-multiple.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/type-boolean-multiple'>;
}
declare module 'command-line-args/es5/test/type-boolean.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/type-boolean'>;
}
declare module 'command-line-args/es5/test/type-none.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/type-none'>;
}
declare module 'command-line-args/es5/test/type-number-multiple.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/type-number-multiple'>;
}
declare module 'command-line-args/es5/test/type-number.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/type-number'>;
}
declare module 'command-line-args/es5/test/type-other-multiple.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/type-other-multiple'>;
}
declare module 'command-line-args/es5/test/type-other.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/type-other'>;
}
declare module 'command-line-args/es5/test/type-string.js' {
  declare module.exports: $Exports<'command-line-args/es5/test/type-string'>;
}
declare module 'command-line-args/example/alias.js' {
  declare module.exports: $Exports<'command-line-args/example/alias'>;
}
declare module 'command-line-args/example/defaultValue.js' {
  declare module.exports: $Exports<'command-line-args/example/defaultValue'>;
}
declare module 'command-line-args/example/group.js' {
  declare module.exports: $Exports<'command-line-args/example/group'>;
}
declare module 'command-line-args/example/multiple.js' {
  declare module.exports: $Exports<'command-line-args/example/multiple'>;
}
declare module 'command-line-args/example/name.js' {
  declare module.exports: $Exports<'command-line-args/example/name'>;
}
declare module 'command-line-args/example/type.js' {
  declare module.exports: $Exports<'command-line-args/example/type'>;
}
declare module 'command-line-args/example/typical.js' {
  declare module.exports: $Exports<'command-line-args/example/typical'>;
}
declare module 'command-line-args/example/validate.js' {
  declare module.exports: $Exports<'command-line-args/example/validate'>;
}
declare module 'command-line-args/index' {
  declare module.exports: $Exports<'command-line-args'>;
}
declare module 'command-line-args/index.js' {
  declare module.exports: $Exports<'command-line-args'>;
}
declare module 'command-line-args/src/bin/cli.js' {
  declare module.exports: $Exports<'command-line-args/src/bin/cli'>;
}
declare module 'command-line-args/src/lib/argv.js' {
  declare module.exports: $Exports<'command-line-args/src/lib/argv'>;
}
declare module 'command-line-args/src/lib/command-line-args.js' {
  declare module.exports: $Exports<'command-line-args/src/lib/command-line-args'>;
}
declare module 'command-line-args/src/lib/definition.js' {
  declare module.exports: $Exports<'command-line-args/src/lib/definition'>;
}
declare module 'command-line-args/src/lib/definitions.js' {
  declare module.exports: $Exports<'command-line-args/src/lib/definitions'>;
}
declare module 'command-line-args/src/lib/option.js' {
  declare module.exports: $Exports<'command-line-args/src/lib/option'>;
}
declare module 'command-line-args/src/test/alias.js' {
  declare module.exports: $Exports<'command-line-args/src/test/alias'>;
}
declare module 'command-line-args/src/test/ambiguous-input.js' {
  declare module.exports: $Exports<'command-line-args/src/test/ambiguous-input'>;
}
declare module 'command-line-args/src/test/bad-input.js' {
  declare module.exports: $Exports<'command-line-args/src/test/bad-input'>;
}
declare module 'command-line-args/src/test/class-argv.js' {
  declare module.exports: $Exports<'command-line-args/src/test/class-argv'>;
}
declare module 'command-line-args/src/test/class-definitions.js' {
  declare module.exports: $Exports<'command-line-args/src/test/class-definitions'>;
}
declare module 'command-line-args/src/test/default-option.js' {
  declare module.exports: $Exports<'command-line-args/src/test/default-option'>;
}
declare module 'command-line-args/src/test/default-value.js' {
  declare module.exports: $Exports<'command-line-args/src/test/default-value'>;
}
declare module 'command-line-args/src/test/detect-process-argv.js' {
  declare module.exports: $Exports<'command-line-args/src/test/detect-process-argv'>;
}
declare module 'command-line-args/src/test/exceptions.js' {
  declare module.exports: $Exports<'command-line-args/src/test/exceptions'>;
}
declare module 'command-line-args/src/test/grouping.js' {
  declare module.exports: $Exports<'command-line-args/src/test/grouping'>;
}
declare module 'command-line-args/src/test/name-alias-mix.js' {
  declare module.exports: $Exports<'command-line-args/src/test/name-alias-mix'>;
}
declare module 'command-line-args/src/test/name-unicode.js' {
  declare module.exports: $Exports<'command-line-args/src/test/name-unicode'>;
}
declare module 'command-line-args/src/test/notations.js' {
  declare module.exports: $Exports<'command-line-args/src/test/notations'>;
}
declare module 'command-line-args/src/test/option.js' {
  declare module.exports: $Exports<'command-line-args/src/test/option'>;
}
declare module 'command-line-args/src/test/type-boolean-multiple.js' {
  declare module.exports: $Exports<'command-line-args/src/test/type-boolean-multiple'>;
}
declare module 'command-line-args/src/test/type-boolean.js' {
  declare module.exports: $Exports<'command-line-args/src/test/type-boolean'>;
}
declare module 'command-line-args/src/test/type-none.js' {
  declare module.exports: $Exports<'command-line-args/src/test/type-none'>;
}
declare module 'command-line-args/src/test/type-number-multiple.js' {
  declare module.exports: $Exports<'command-line-args/src/test/type-number-multiple'>;
}
declare module 'command-line-args/src/test/type-number.js' {
  declare module.exports: $Exports<'command-line-args/src/test/type-number'>;
}
declare module 'command-line-args/src/test/type-other-multiple.js' {
  declare module.exports: $Exports<'command-line-args/src/test/type-other-multiple'>;
}
declare module 'command-line-args/src/test/type-other.js' {
  declare module.exports: $Exports<'command-line-args/src/test/type-other'>;
}
declare module 'command-line-args/src/test/type-string.js' {
  declare module.exports: $Exports<'command-line-args/src/test/type-string'>;
}
declare module 'command-line-args/test.js' {
  declare module.exports: $Exports<'command-line-args/test'>;
}
