// flow-typed signature: 89f2c46f44b4ea836d11978ffaaad5d4
// flow-typed version: <<STUB>>/openapi-flowtype-definition_v^1.0.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'openapi-flowtype-definition'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'openapi-flowtype-definition' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'openapi-flowtype-definition/example/example' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/Definitions' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/Example' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/ExternalDocumentation' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/Headers' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/Info' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/Items' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/Operation' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/ParametersDefinition' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/Paths' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/ProtocolScheme' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/Reference' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/ResponsesDefinition' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/Schema' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/Scopes' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/SecurityDefinitions' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/SecurityRequirement' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/Swagger' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/Tag' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/test/swagger-api-with-examples' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/test/swagger-petstore-expanded' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/test/swagger-petstore-minimal' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/test/swagger-petstore-simple' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/test/swagger-petstore-with-external-docs' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/test/swagger-petstore' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/test/swagger-uber' {
  declare module.exports: any;
}

declare module 'openapi-flowtype-definition/src/XML' {
  declare module.exports: any;
}

// Filename aliases
declare module 'openapi-flowtype-definition/example/example.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/example/example'>;
}
declare module 'openapi-flowtype-definition/index' {
  declare module.exports: $Exports<'openapi-flowtype-definition'>;
}
declare module 'openapi-flowtype-definition/index.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition'>;
}
declare module 'openapi-flowtype-definition/src/Definitions.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/Definitions'>;
}
declare module 'openapi-flowtype-definition/src/Example.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/Example'>;
}
declare module 'openapi-flowtype-definition/src/ExternalDocumentation.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/ExternalDocumentation'>;
}
declare module 'openapi-flowtype-definition/src/Headers.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/Headers'>;
}
declare module 'openapi-flowtype-definition/src/Info.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/Info'>;
}
declare module 'openapi-flowtype-definition/src/Items.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/Items'>;
}
declare module 'openapi-flowtype-definition/src/Operation.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/Operation'>;
}
declare module 'openapi-flowtype-definition/src/ParametersDefinition.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/ParametersDefinition'>;
}
declare module 'openapi-flowtype-definition/src/Paths.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/Paths'>;
}
declare module 'openapi-flowtype-definition/src/ProtocolScheme.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/ProtocolScheme'>;
}
declare module 'openapi-flowtype-definition/src/Reference.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/Reference'>;
}
declare module 'openapi-flowtype-definition/src/ResponsesDefinition.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/ResponsesDefinition'>;
}
declare module 'openapi-flowtype-definition/src/Schema.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/Schema'>;
}
declare module 'openapi-flowtype-definition/src/Scopes.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/Scopes'>;
}
declare module 'openapi-flowtype-definition/src/SecurityDefinitions.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/SecurityDefinitions'>;
}
declare module 'openapi-flowtype-definition/src/SecurityRequirement.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/SecurityRequirement'>;
}
declare module 'openapi-flowtype-definition/src/Swagger.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/Swagger'>;
}
declare module 'openapi-flowtype-definition/src/Tag.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/Tag'>;
}
declare module 'openapi-flowtype-definition/src/test/swagger-api-with-examples.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/test/swagger-api-with-examples'>;
}
declare module 'openapi-flowtype-definition/src/test/swagger-petstore-expanded.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/test/swagger-petstore-expanded'>;
}
declare module 'openapi-flowtype-definition/src/test/swagger-petstore-minimal.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/test/swagger-petstore-minimal'>;
}
declare module 'openapi-flowtype-definition/src/test/swagger-petstore-simple.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/test/swagger-petstore-simple'>;
}
declare module 'openapi-flowtype-definition/src/test/swagger-petstore-with-external-docs.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/test/swagger-petstore-with-external-docs'>;
}
declare module 'openapi-flowtype-definition/src/test/swagger-petstore.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/test/swagger-petstore'>;
}
declare module 'openapi-flowtype-definition/src/test/swagger-uber.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/test/swagger-uber'>;
}
declare module 'openapi-flowtype-definition/src/XML.js' {
  declare module.exports: $Exports<'openapi-flowtype-definition/src/XML'>;
}
